SwfWindow("Inventory Management").SwfObject("tcMain").Click 35,114 @@ hightlight id_;_1381268_;_script infofile_;_ZIP::ssf1.xml_;_
SwfWindow("Inventory Management").SwfObject("tcMain").Click 49,191 @@ hightlight id_;_1381268_;_script infofile_;_ZIP::ssf2.xml_;_
SwfWindow("Inventory Management").SwfObject("tcMain").Click 40,268 @@ hightlight id_;_1381268_;_script infofile_;_ZIP::ssf3.xml_;_
SwfWindow("Inventory Management").SwfObject("tcMain").Click 40,343 @@ hightlight id_;_1381268_;_script infofile_;_ZIP::ssf4.xml_;_
SwfWindow("Inventory Management").SwfObject("tcMain").Click 38,32 @@ hightlight id_;_1381268_;_script infofile_;_ZIP::ssf5.xml_;_
SwfWindow("Inventory Management").SwfObject("ultraListView1").Click 82,36 @@ hightlight id_;_983572_;_script infofile_;_ZIP::ssf6.xml_;_
SwfWindow("Inventory Management").SwfObject("ultraListView1").Click 297,38 @@ hightlight id_;_983572_;_script infofile_;_ZIP::ssf7.xml_;_
SwfWindow("Inventory Management").SwfObject("ultraListView1").Click 74,122 @@ hightlight id_;_983572_;_script infofile_;_ZIP::ssf8.xml_;_
SwfWindow("Inventory Management").SwfObject("ultraListView1").Click 72,108 @@ hightlight id_;_983572_;_script infofile_;_ZIP::ssf9.xml_;_
SwfWindow("Inventory Management").SwfObject("ultraListView1").Click 82,167 @@ hightlight id_;_983572_;_script infofile_;_ZIP::ssf10.xml_;_
SwfWindow("Inventory Management").SwfObject("ultraListView1").Click 234,167 @@ hightlight id_;_983572_;_script infofile_;_ZIP::ssf11.xml_;_
SwfWindow("Inventory Management").SwfObject("Orders").Click 183,115 @@ hightlight id_;_1967894_;_script infofile_;_ZIP::ssf12.xml_;_
SwfWindow("Inventory Management").SwfObject("ultraDayView1").Click 205,55 @@ hightlight id_;_1315678_;_script infofile_;_ZIP::ssf13.xml_;_
SwfWindow("Inventory Management").SwfObject("tcOrders").Click 104,103 @@ hightlight id_;_6619898_;_script infofile_;_ZIP::ssf14.xml_;_
SwfWindow("Inventory Management").SwfObject("tcOrders").Click 89,61 @@ hightlight id_;_6619898_;_script infofile_;_ZIP::ssf15.xml_;_
SwfWindow("Inventory Management").SwfObject("tcOrders").Click 91,25 @@ hightlight id_;_6619898_;_script infofile_;_ZIP::ssf16.xml_;_
SwfWindow("Inventory Management").SwfObject("tcMain").Click 38,33 @@ hightlight id_;_1381268_;_script infofile_;_ZIP::ssf17.xml_;_
SwfWindow("Inventory Management").SwfObject("Contacts").Click 155,150 @@ hightlight id_;_1050608_;_script infofile_;_ZIP::ssf18.xml_;_
SwfWindow("Inventory Management").SwfObject("tcCustomers").Click 87,104 @@ hightlight id_;_4784236_;_script infofile_;_ZIP::ssf19.xml_;_
SwfWindow("Inventory Management").SwfObject("tcCustomers").Click 85,62 @@ hightlight id_;_4784236_;_script infofile_;_ZIP::ssf20.xml_;_
SwfWindow("Inventory Management").SwfObject("tcCustomers").Click 83,142 @@ hightlight id_;_4784236_;_script infofile_;_ZIP::ssf21.xml_;_
SwfWindow("Inventory Management").SwfTable("gridContacts").SelectRow 2 @@ hightlight id_;_1179690_;_script infofile_;_ZIP::ssf22.xml_;_
SwfWindow("Inventory Management").SwfTable("gridContacts").SelectRow 8 @@ hightlight id_;_1179690_;_script infofile_;_ZIP::ssf23.xml_;_
SwfWindow("Inventory Management").SwfObject("tcMain").Click 28,42 @@ hightlight id_;_1381268_;_script infofile_;_ZIP::ssf24.xml_;_
SwfWindow("Inventory Management").SwfObject("Reports").Click 35,118 @@ hightlight id_;_262810_;_script infofile_;_ZIP::ssf25.xml_;_
SwfWindow("Inventory Management").SwfTable("gridReports").SelectRow 26 @@ hightlight id_;_788176_;_script infofile_;_ZIP::ssf26.xml_;_
SwfWindow("Inventory Management").SwfObject("tcMain").Click 27,41 @@ hightlight id_;_1381268_;_script infofile_;_ZIP::ssf27.xml_;_
SwfWindow("Inventory Management").SwfObject("Orders").Click 155,135 @@ hightlight id_;_1967894_;_script infofile_;_ZIP::ssf28.xml_;_
